; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py
; RUN: opt -passes="print<cost-model>" -cost-kind=all 2>&1 -disable-output -mtriple=z80 < %s | FileCheck %s
;
; Z80 scalar-integer arithmetic costs (ravn/llvm-z80#177).  Also the regression
; guard that `opt -mtriple=z80` does not crash (it did until the
; Z80AutoStaticStack pass-registration name was disambiguated from its cl::opt).

target datalayout = "e-m:o-p:16:8-i16:8-i32:8-i64:8-i128:8-f32:8-f64:8-n8:16"
target triple = "z80"

define void @i8(i8 %a, i8 %b) {
; CHECK-LABEL: 'i8'
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %add = add i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %sub = sub i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 4 for: %mul = mul i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %and = and i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %or = or i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %xor = xor i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %shl = shl i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %lshr = lshr i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %ashr = ashr i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of RThru:1 CodeSize:4 Lat:4 SizeLat:4 for: %udiv = udiv i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of RThru:1 CodeSize:4 Lat:4 SizeLat:4 for: %sdiv = sdiv i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: ret void
;
  %add = add i8 %a, %b
  %sub = sub i8 %a, %b
  %mul = mul i8 %a, %b
  %and = and i8 %a, %b
  %or  = or  i8 %a, %b
  %xor = xor i8 %a, %b
  %shl = shl i8 %a, %b
  %lshr = lshr i8 %a, %b
  %ashr = ashr i8 %a, %b
  %udiv = udiv i8 %a, %b
  %sdiv = sdiv i8 %a, %b
  ret void
}

define void @i16(i16 %a, i16 %b) {
; CHECK-LABEL: 'i16'
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %add = add i16 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %sub = sub i16 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 4 for: %mul = mul i16 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %and = and i16 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %shl = shl i16 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of RThru:1 CodeSize:4 Lat:4 SizeLat:4 for: %udiv = udiv i16 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 1 for: ret void
;
  %add = add i16 %a, %b
  %sub = sub i16 %a, %b
  %mul = mul i16 %a, %b
  %and = and i16 %a, %b
  %shl = shl i16 %a, %b
  %udiv = udiv i16 %a, %b
  ret void
}
