; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py
; RUN: opt -passes="print<cost-model>" -cost-kind=all 2>&1 -disable-output -mtriple=z80 < %s | FileCheck %s
; Z80 integer cast costs (ravn/llvm-z80#177): trunc free; zext clears high
; bytes; sext computes+splats the sign, scaling with width (monotonic).
target datalayout = "e-m:o-p:16:8-i16:8-i32:8-i64:8-i128:8-f32:8-f64:8-n8:16"
target triple = "z80"
define void @casts(i8 %a, i16 %h, i32 %w, i64 %q) {
; CHECK-LABEL: 'casts'
; CHECK-NEXT:  Cost Model: Found costs of 0 for: %t16_8 = trunc i16 %h to i8
; CHECK-NEXT:  Cost Model: Found costs of 0 for: %t32_16 = trunc i32 %w to i16
; CHECK-NEXT:  Cost Model: Found costs of 0 for: %t32_8 = trunc i32 %w to i8
; CHECK-NEXT:  Cost Model: Found costs of 0 for: %t64_32 = trunc i64 %q to i32
; CHECK-NEXT:  Cost Model: Found costs of 0 for: %z8_16 = zext i8 %a to i16
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %z8_32 = zext i8 %a to i32
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %z16_32 = zext i16 %h to i32
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %z32_64 = zext i32 %w to i64
; CHECK-NEXT:  Cost Model: Found costs of 2 for: %s8_16 = sext i8 %a to i16
; CHECK-NEXT:  Cost Model: Found costs of 4 for: %s8_32 = sext i8 %a to i32
; CHECK-NEXT:  Cost Model: Found costs of 3 for: %s16_32 = sext i16 %h to i32
; CHECK-NEXT:  Cost Model: Found costs of 5 for: %s32_64 = sext i32 %w to i64
; CHECK-NEXT:  Cost Model: Found costs of 1 for: ret void
;
  %t16_8  = trunc i16 %h to i8
  %t32_16 = trunc i32 %w to i16
  %t32_8  = trunc i32 %w to i8
  %t64_32 = trunc i64 %q to i32
  %z8_16  = zext i8 %a to i16
  %z8_32  = zext i8 %a to i32
  %z16_32 = zext i16 %h to i32
  %z32_64 = zext i32 %w to i64
  %s8_16  = sext i8 %a to i16
  %s8_32  = sext i8 %a to i32
  %s16_32 = sext i16 %h to i32
  %s32_64 = sext i32 %w to i64
  ret void
}
