; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py
; RUN: opt -passes="print<cost-model>" -cost-kind=all 2>&1 -disable-output -mtriple=z80 < %s | FileCheck %s
;
; Z80 has no barrel shifter (ravn/llvm-z80#177): a shift is N single-bit
; shift/rotate ops, and a variable shift count becomes a runtime loop.  Costs
; must reflect that -- the BasicTTIImpl default of 1 is far too cheap.

target datalayout = "e-m:o-p:16:8-i16:8-i32:8-i64:8-i128:8-f32:8-f64:8-n8:16"
target triple = "z80"

define void @const_amt(i8 %a, i16 %h) {
; CHECK-LABEL: 'const_amt'
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %s1 = shl i8 %a, 1
; CHECK-NEXT:  Cost Model: Found costs of 3 for: %s3 = shl i8 %a, 3
; CHECK-NEXT:  Cost Model: Found costs of 7 for: %s7 = shl i8 %a, 7
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %r1 = lshr i8 %a, 1
; CHECK-NEXT:  Cost Model: Found costs of 1 for: %a1 = ashr i8 %a, 1
; CHECK-NEXT:  Cost Model: Found costs of 2 for: %h1 = shl i16 %h, 1
; CHECK-NEXT:  Cost Model: Found costs of 16 for: %h12 = shl i16 %h, 12
; CHECK-NEXT:  Cost Model: Found costs of 1 for: ret void
;
  %s1  = shl  i8  %a, 1
  %s3  = shl  i8  %a, 3
  %s7  = shl  i8  %a, 7
  %r1  = lshr i8  %a, 1
  %a1  = ashr i8  %a, 1
  %h1  = shl  i16 %h, 1
  %h12 = shl  i16 %h, 12
  ret void
}

define void @var_amt(i8 %a, i8 %b, i16 %h, i16 %hb) {
; CHECK-LABEL: 'var_amt'
; CHECK-NEXT:  Cost Model: Found costs of 4 for: %s = shl i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 4 for: %r = lshr i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 4 for: %t = ashr i8 %a, %b
; CHECK-NEXT:  Cost Model: Found costs of 8 for: %v = shl i16 %h, %hb
; CHECK-NEXT:  Cost Model: Found costs of 1 for: ret void
;
  %s = shl  i8  %a, %b
  %r = lshr i8  %a, %b
  %t = ashr i8  %a, %b
  %v = shl  i16 %h, %hb
  ret void
}
