; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=aggressive-instcombine -S | FileCheck %s

; Fork extension on top of llvm/llvm-project#204920: signed icmp outside-graph
; users are admitted when the comparison carries the `samesign` flag, with the
; soundness gate tightened so each operand fits in MinBitWidth-1 bits (sign
; bit clear at the narrow width).
;
; All chains root at `zext i8 to i16` so the tests are independent of
; llvm/llvm-project#204915 (Argument-as-leaf).

declare void @sink(i8)

;; --- Positive: samesign sgt against a constant < 128 narrows ---

define i1 @samesign_sgt_const(i8 %xb) {
; CHECK-LABEL: @samesign_sgt_const(
; CHECK-NEXT:    [[X_T:%.*]] = and i8 [[XB:%.*]], 15
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i8 [[X_T]], 7
; CHECK-NEXT:    call void @sink(i8 [[X_T]])
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %x = zext i8 %xb to i16
  %m = and i16 %x, 15
  %cmp = icmp samesign sgt i16 %m, 7
  %t = trunc i16 %m to i8
  call void @sink(i8 %t)
  ret i1 %cmp
}

;; --- Positive: samesign sle against a constant < 128 narrows ---

define i1 @samesign_sle_const(i8 %xb) {
; CHECK-LABEL: @samesign_sle_const(
; CHECK-NEXT:    [[X_T:%.*]] = and i8 [[XB:%.*]], 63
; CHECK-NEXT:    [[CMP:%.*]] = icmp sle i8 [[X_T]], 42
; CHECK-NEXT:    call void @sink(i8 [[X_T]])
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %x = zext i8 %xb to i16
  %m = and i16 %x, 63
  %cmp = icmp samesign sle i16 %m, 42
  %t = trunc i16 %m to i8
  call void @sink(i8 %t)
  ret i1 %cmp
}

;; --- Negative: signed predicate WITHOUT samesign — predicate gate rejects ---

define i1 @signed_no_samesign(i8 %xb) {
; CHECK-LABEL: @signed_no_samesign(
; CHECK-NEXT:    [[X:%.*]] = zext i8 [[XB:%.*]] to i16
; CHECK-NEXT:    [[M:%.*]] = and i16 [[X]], 15
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i16 [[M]], 7
; CHECK-NEXT:    [[T:%.*]] = trunc i16 [[M]] to i8
; CHECK-NEXT:    call void @sink(i8 [[T]])
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %x = zext i8 %xb to i16
  %m = and i16 %x, 15
  %cmp = icmp sgt i16 %m, 7
  %t = trunc i16 %m to i8
  call void @sink(i8 %t)
  ret i1 %cmp
}

;; --- Negative: samesign sgt against 200 (> 127) — FitBits=7 gate rejects ---
;; Without the tighter FitBits, narrowing would observe 200 as -56 at i8 and
;; flip the sgt result; the gate must prevent the rewrite.

define i1 @samesign_sgt_oversize_const(i8 %xb) {
; CHECK-LABEL: @samesign_sgt_oversize_const(
; CHECK-NEXT:    [[X:%.*]] = zext i8 [[XB:%.*]] to i16
; CHECK-NEXT:    [[M:%.*]] = and i16 [[X]], 255
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign sgt i16 [[M]], 200
; CHECK-NEXT:    [[T:%.*]] = trunc i16 [[M]] to i8
; CHECK-NEXT:    call void @sink(i8 [[T]])
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %x = zext i8 %xb to i16
  %m = and i16 %x, 255
  %cmp = icmp samesign sgt i16 %m, 200
  %t = trunc i16 %m to i8
  call void @sink(i8 %t)
  ret i1 %cmp
}

;; --- Negative: samesign sgt where the in-graph operand can reach 200 ---
;; Graph-side KnownBits show bit 7 may be set; FitBits=7 rejects.

define i1 @samesign_sgt_graph_too_wide(i8 %xb) {
; CHECK-LABEL: @samesign_sgt_graph_too_wide(
; CHECK-NEXT:    [[X:%.*]] = zext i8 [[XB:%.*]] to i16
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign sgt i16 [[X]], 7
; CHECK-NEXT:    [[T:%.*]] = trunc i16 [[X]] to i8
; CHECK-NEXT:    call void @sink(i8 [[T]])
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %x = zext i8 %xb to i16
  %cmp = icmp samesign sgt i16 %x, 7
  %t = trunc i16 %x to i8
  call void @sink(i8 %t)
  ret i1 %cmp
}
