; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=aggressive-instcombine -S | FileCheck %s

; Fork extension on top of llvm/llvm-project#204920: outside-graph
; `(and X, Const)` users where X is in-graph and Const fits in the narrow
; width are admitted; rewritten as `(zext (and Xnarrow, ConstTrunc) to OrigTy)`.
; Sound regardless of the graph-side KnownBits — the AND clamps the value
; to the mask unconditionally.

declare void @sink(i8)
declare void @sink16(i16)

;; --- Positive: mask = 0xFF (fits in i8), graph-side unproven ---
;; The mask discards X's high bits before any outside consumer sees it, so
;; soundness does not depend on the in-graph value being provably narrow.

define i16 @andmask_fits_unproven(i8 %xb) {
; CHECK-LABEL: @andmask_fits_unproven(
; CHECK-NEXT:    [[SHL:%.*]] = shl i8 [[XB:%.*]], 1
; CHECK-NEXT:    [[LSHR:%.*]] = lshr i8 [[XB]], 7
; CHECK-NEXT:    [[ROT_T:%.*]] = or i8 [[SHL]], [[LSHR]]
; CHECK-NEXT:    [[MASK_T:%.*]] = and i8 [[ROT_T]], -1
; CHECK-NEXT:    [[Z:%.*]] = zext i8 [[MASK_T]] to i16
; CHECK-NEXT:    call void @sink(i8 [[ROT_T]])
; CHECK-NEXT:    ret i16 [[Z]]
;
  %x = zext i8 %xb to i16
  %shl = shl i16 %x, 1
  %lshr = lshr i16 %x, 7
  %rot = or i16 %shl, %lshr
  %mask = and i16 %rot, 255
  %t = trunc i16 %rot to i8
  call void @sink(i8 %t)
  ret i16 %mask
}

;; --- Positive: mask = 0x0F ---

define i16 @andmask_smaller(i8 %xb) {
; CHECK-LABEL: @andmask_smaller(
; CHECK-NEXT:    [[ADD_T:%.*]] = add i8 [[X_T:%.*]], 1
; CHECK-NEXT:    [[MASK_T:%.*]] = and i8 [[ADD_T]], 15
; CHECK-NEXT:    [[Z:%.*]] = zext i8 [[MASK_T]] to i16
; CHECK-NEXT:    call void @sink(i8 [[ADD_T]])
; CHECK-NEXT:    ret i16 [[Z]]
;
  %x = zext i8 %xb to i16
  %add = add i16 %x, 1
  %mask = and i16 %add, 15
  %t = trunc i16 %add to i8
  call void @sink(i8 %t)
  ret i16 %mask
}

;; --- Negative: mask = 0x1FF (9 bits) — does NOT fit in i8, gate rejects ---

define i16 @andmask_too_wide(i8 %xb) {
; CHECK-LABEL: @andmask_too_wide(
; CHECK-NEXT:    [[X:%.*]] = zext i8 [[XB:%.*]] to i16
; CHECK-NEXT:    [[ADD:%.*]] = add i16 [[X]], 1
; CHECK-NEXT:    [[MASK:%.*]] = and i16 [[ADD]], 511
; CHECK-NEXT:    [[T:%.*]] = trunc i16 [[ADD]] to i8
; CHECK-NEXT:    call void @sink(i8 [[T]])
; CHECK-NEXT:    ret i16 [[MASK]]
;
  %x = zext i8 %xb to i16
  %add = add i16 %x, 1
  %mask = and i16 %add, 511
  %t = trunc i16 %add to i8
  call void @sink(i8 %t)
  ret i16 %mask
}

;; --- Negative: outside-graph user is OR (not AND) — gate rejects ---

define i16 @or_outside_not_admitted(i8 %xb) {
; CHECK-LABEL: @or_outside_not_admitted(
; CHECK-NEXT:    [[X:%.*]] = zext i8 [[XB:%.*]] to i16
; CHECK-NEXT:    [[ADD:%.*]] = add i16 [[X]], 1
; CHECK-NEXT:    [[OR:%.*]] = or i16 [[ADD]], 240
; CHECK-NEXT:    [[T:%.*]] = trunc i16 [[ADD]] to i8
; CHECK-NEXT:    call void @sink(i8 [[T]])
; CHECK-NEXT:    ret i16 [[OR]]
;
  %x = zext i8 %xb to i16
  %add = add i16 %x, 1
  %or = or i16 %add, 240
  %t = trunc i16 %add to i8
  call void @sink(i8 %t)
  ret i16 %or
}

;; --- Mixed shape, icmp-gate dominates: when both outside-user kinds reach
;; the same in-graph value AND the icmp soundness gate fails (here %add =
;; %x + 1 has KnownBits.getMaxValue.activeBits = 9 > MinBitWidth = 8), the
;; whole rewrite is rejected.  Pins the property that the icmp gate's
;; nullptr return aborts the and-mask path too — by design, since
;; getBestTruncatedType is all-or-nothing per chain.

define i1 @mixed_andmask_and_icmp_gate_fails(i8 %xb, ptr %p) {
; CHECK-LABEL: @mixed_andmask_and_icmp_gate_fails(
; CHECK-NEXT:    [[Z:%.*]] = zext i8 [[MASK_T:%.*]] to i16
; CHECK-NEXT:    [[ADD:%.*]] = add i16 [[Z]], 1
; CHECK-NEXT:    [[MASK:%.*]] = and i16 [[ADD]], 15
; CHECK-NEXT:    store i16 [[MASK]], ptr [[P:%.*]], align 2
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i16 [[ADD]], 7
; CHECK-NEXT:    [[ADD_T:%.*]] = trunc i16 [[ADD]] to i8
; CHECK-NEXT:    call void @sink(i8 [[ADD_T]])
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %x = zext i8 %xb to i16
  %add = add i16 %x, 1
  %mask = and i16 %add, 15
  store i16 %mask, ptr %p
  %cmp = icmp eq i16 %add, 7
  %t = trunc i16 %add to i8
  call void @sink(i8 %t)
  ret i1 %cmp
}
