; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; sext(a) == sext(b)  <=>  a == b  (sext is injective).  InstCombine already
; narrows the canonical `icmp eq (sext a), (sext b)` form; these tests cover the
; `ashr(shl x, N), N` sign-extend-in-register idiom (LLVM has no sext-inreg
; instruction, so that shift pair is `(char)c`'s canonical form), which the
; equality narrowing previously missed.  Missing it left `*s == (char)c` in
; strrchr as a 16-bit compare, over-constraining the Z80 register allocator.

define i1 @sext_inreg_vs_sext(i16 %c, i8 %s) {
; CHECK-LABEL: @sext_inreg_vs_sext(
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i16 [[C:%.*]] to i8
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i8 [[S:%.*]], [[TMP1]]
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %shl = shl i16 %c, 8
  %ashr = ashr i16 %shl, 8
  %ss = sext i8 %s to i16
  %cmp = icmp eq i16 %ashr, %ss
  ret i1 %cmp
}

define i1 @sext_inreg_vs_sext_ne(i16 %c, i8 %s) {
; CHECK-LABEL: @sext_inreg_vs_sext_ne(
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i16 [[C:%.*]] to i8
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i8 [[S:%.*]], [[TMP1]]
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %shl = shl i16 %c, 8
  %ashr = ashr i16 %shl, 8
  %ss = sext i8 %s to i16
  %cmp = icmp ne i16 %ashr, %ss
  ret i1 %cmp
}

define i1 @both_inreg(i16 %a, i16 %b) {
; CHECK-LABEL: @both_inreg(
; CHECK-NEXT:    [[CMP_UNSHIFTED:%.*]] = xor i16 [[A:%.*]], [[B:%.*]]
; CHECK-NEXT:    [[CMP_MASK:%.*]] = and i16 [[CMP_UNSHIFTED]], 255
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i16 [[CMP_MASK]], 0
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %sa = shl i16 %a, 8
  %aa = ashr i16 %sa, 8
  %sb = shl i16 %b, 8
  %ab = ashr i16 %sb, 8
  %cmp = icmp eq i16 %aa, %ab
  ret i1 %cmp
}

; Different sign-bit counts (i8-wide vs i4-wide) is NOT a provable equality of
; the low bits, so the compare must stay 16-bit.
define i1 @mismatched_srcbits(i16 %c, i8 %s) {
; CHECK-LABEL: @mismatched_srcbits(
; CHECK-NEXT:    [[SHL:%.*]] = shl i16 [[C:%.*]], 12
; CHECK-NEXT:    [[ASHR:%.*]] = ashr exact i16 [[SHL]], 12
; CHECK-NEXT:    [[SS:%.*]] = sext i8 [[S:%.*]] to i16
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i16 [[ASHR]], [[SS]]
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %shl = shl i16 %c, 12
  %ashr = ashr i16 %shl, 12
  %ss = sext i8 %s to i16
  %cmp = icmp eq i16 %ashr, %ss
  ret i1 %cmp
}

; The wide idiom result feeds another user, so narrowing would not remove the
; 16-bit shift chain; leave the compare alone.
define i1 @multiuse_idiom(i16 %c, i8 %s, ptr %p) {
; CHECK-LABEL: @multiuse_idiom(
; CHECK-NEXT:    [[SHL:%.*]] = shl i16 [[C:%.*]], 8
; CHECK-NEXT:    [[ASHR:%.*]] = ashr exact i16 [[SHL]], 8
; CHECK-NEXT:    store i16 [[ASHR]], ptr [[P:%.*]], align 2
; CHECK-NEXT:    [[SS:%.*]] = sext i8 [[S:%.*]] to i16
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i16 [[ASHR]], [[SS]]
; CHECK-NEXT:    ret i1 [[CMP]]
;
  %shl = shl i16 %c, 8
  %ashr = ashr i16 %shl, 8
  store i16 %ashr, ptr %p
  %ss = sext i8 %s to i16
  %cmp = icmp eq i16 %ashr, %ss
  ret i1 %cmp
}
