# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=z80 -run-pass=postrapseudos -verify-machineinstrs %s -o - \
# RUN:     | FileCheck %s
# XFAIL: *
#
# ravn/llvm-z80#239 site 6: copyPhysReg SP -> BC|DE used to emit an
# unconditional PUSH_HL with no liveness gate.  When HL is undef at the
# COPY point, the PUSH_HL would read an undefined $hl and trip
# -verify-machineinstrs.
#
# The shape:
#
#   if (FlagsLive)
#     BuildMI(... PUSH_AF);
#   BuildMI(... PUSH_HL);                        // <-- unconditional
#   BuildMI(... LD_HL_nn).addImm(SPComp + 2);
#   BuildMI(... ADD_HL_SP);
#   BuildMI(... LD r,H);                         // LD B,H or LD D,H
#   BuildMI(... LD r,L);                         // LD C,L or LD E,L
#   BuildMI(... POP_HL);
#   if (FlagsLive)
#     BuildMI(... POP_AF);
#
# Fix: gate the PUSH_HL/POP_HL pair on H/L liveness at the COPY point.
# When both halves are dead the save is skipped (HLComp = 0).  When only
# one half is live, the dead half is IMPLICIT_DEF'd before PUSH_HL
# (mirrors the SP-relative GR8 expanders for #210/#212 and site 1 above).

--- |
  target triple = "z80"
  define void @copy_sp_to_bc_hl_undef() { ret void }
...
---
name:            copy_sp_to_bc_hl_undef
alignment:       1
tracksRegLiveness: true
noVRegs:         true
body:             |
  bb.0:
    ; No live-ins -- HL is undef coming into the COPY.  The COPY $bc = $sp
    ; goes through copyPhysReg's SP -> BC|DE path which unconditionally
    ; emits PUSH_HL/POP_HL.
    ; CHECK-LABEL: name: copy_sp_to_bc_hl_undef
    ; CHECK: PUSH_HL implicit undef $hl
    ; CHECK-NEXT: $hl = LD_rr_nn 2
    ; CHECK-NEXT: ADD_HL_SP implicit-def $hl, implicit-def $flags, implicit $hl, implicit $sp
    ; CHECK-NEXT: $b = LD_r_r $h
    ; CHECK-NEXT: $c = LD_r_r $l
    ; CHECK-NEXT: POP_HL implicit-def $hl
    ; CHECK-NEXT: RET implicit $bc
    $bc = COPY $sp
    RET implicit $bc
...

# HL is undef, so no PUSH_HL is emitted.  The lowering reduces to
# LD HL,0; ADD HL,SP; LD B,H; LD C,L (HL is "left as scratch," which is
# fine because HL was already undef — no caller invariant is broken).
#
# CHECK-LABEL: name: copy_sp_to_bc_hl_undef
# CHECK-NOT: PUSH_HL
# CHECK: LD_HL_nn 0
# CHECK: ADD_HL_SP
# CHECK: LD_B_H
# CHECK: LD_C_L
# CHECK-NOT: POP_HL
