; XFAIL: *
; RUN: llc -mtriple=z80 -O2 -z80-asm-format=sdasz80 < %s | FileCheck %s
;
; ravn/llvm-z80#243: LD_IYd_r / LD_r_IYd (and the IX variants) do not declare
; IX or IY in their Uses field in Z80InstrInfo.td.  This makes the IX-transfer
; peephole in Z80LateOptimization.cpp (Form 2, ~line 4739) blind to IY uses
; that appear after the closing COPY16_PUSHPOP.  The liveness check
; `computeRegisterLiveness(IY, after_end_copy)` returns LQR_Dead even though
; a downstream LD_IYd_A reads the address from IY, so the peephole drops the
; `$iy = buf+idx` assignment while keeping `ld (iy+0), a`.
;
; Trigger conditions (all three required simultaneously):
;   1. Greedy RA allocates a `hli`-class virtual register to $iy.
;   2. The virtual register is the address for both a load and a store.
;   3. AND_HLind forces a COPY16_PUSHPOP $iy,$hl ... COPY16_PUSHPOP $hl,$iy
;      pair around the CPL-based mask computation.
; These three coincide at -Os (size-optimised builds) but not at -O0/-O1/-O2
; because at lower opts the frame pointer keeps the address on the stack or
; the virtual register is coloured $hl directly.
;
; Smallest C repro (trigger: -Os):
;   static unsigned char buf[16];
;   void test(unsigned char idx, unsigned char tail) {
;       unsigned char mask = (unsigned char)(0xFF << (8 - tail));
;       buf[idx] &= (unsigned char)~mask;
;   }
;
; Wrong output at -Os (before fix):
;   add  hl, de          ; HL = buf+idx  -- address correctly computed in HL
;   push hl              ; HL saved
;   cpl                  ; A = ~mask
;   pop  hl              ; HL restored = buf+idx
;   and  (hl)            ; A = buf[idx] & ~mask  -- READ via HL: correct
;   ld   (iy+0), a       ; WRITE via IY: WRONG -- IY was never set to buf+idx
;
; Expected output after fix:
;   ...
;   and  (hl)
;   ld   (hl), a         ; WRITE via HL: correct
;
; Root cause:
;   Z80InstrInfo.td lines 323-338, 347-362: every LD_IXd_r, LD_IYd_r (stores)
;   and LD_r_IXd, LD_r_IYd (loads) is missing IX or IY from its Uses list.
;   Contrast: AND_HLind at Z80InstrCommon.td:223 correctly has `let Uses = [A, HL]`.
;   The missing Use makes:
;     (a) computeRegisterLiveness(IY, after_end_copy) return LQR_Dead ->
;         IX-transfer peephole (Form 2, Z80LateOptimization.cpp:~4781) fires.
;     (b) touchesReg(*LD_r_IYd, IY) return false -> peephole scan walks past
;         load instructions that use IY as an address (secondary hazard).
;
; XFAIL because the fix has not landed yet.  When it lands, remove XFAIL and
; change the CHECK below to verify `ld (hl), a` (no IY in the store path).

; The IR below is generated by: clang --target=z80 -Os -S -emit-llvm (with
; the `optsize` attribute already present).  Feed to llc -O2 to exercise the
; same IY-allocation path without the clang front-end.

target datalayout = "e-m:o-p:16:8-i16:8-i32:8-i64:8-i128:8-f32:8-f64:8-n8:16"
target triple = "z80"

@buf = internal unnamed_addr global [16 x i8] zeroinitializer, align 1

; Function Attrs: optsize
define dso_local void @test(i8 noundef zeroext %0, i8 noundef zeroext %1) local_unnamed_addr #0 {
  %3 = zext i8 %1 to i16
  %4 = sub nsw i16 8, %3
  %5 = shl nuw i16 255, %4
  %6 = zext i8 %0 to i16
  %7 = getelementptr inbounds nuw i8, ptr @buf, i16 %6
  %8 = load i8, ptr %7, align 1
  %9 = trunc i16 %5 to i8
  %10 = xor i8 %9, -1
  %11 = and i8 %8, %10
  store i8 %11, ptr %7, align 1
  ret void
}

attributes #0 = { optsize "target-features"="+z80" }

; After the bug is fixed, the store must use HL (the address is already in HL
; at the point of AND_HLind and must not move to an uninitialised IY).
;
; CHECK-LABEL: _test:
; CHECK:       and (hl)
; CHECK-NEXT:  ld (hl), a
; CHECK-NOT:   ld (iy


